In [60]:
import wand.image
from PIL import Image
from PIL.ExifTags import GPSTAGS
from PIL.ExifTags import TAGS
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
import os

In [25]:
def get_exif(filename):
    image = Image.open(filename)
    image.verify()
    return image._getexif()

def get_geotagging(exif):
    if not exif:
        raise ValueError("No EXIF metadata found")

    geotagging = {}
    for (idx, tag) in TAGS.items():
        if tag == 'GPSInfo':
            if idx not in exif:
                raise ValueError("No EXIF geotagging found")

            for (key, val) in GPSTAGS.items():
                if key in exif[idx]:
                    geotagging[val] = exif[idx][key]

    return geotagging
def get_decimal_from_dms(dms, ref):

    degrees = dms[0][0] / dms[0][1]
    minutes = dms[1][0] / dms[1][1] / 60.0
    seconds = dms[2][0] / dms[2][1] / 3600.0

    if ref in ['S', 'W']:
        degrees = -degrees
        minutes = -minutes
        seconds = -seconds

    return round(degrees + minutes + seconds, 5)

def get_coordinates(geotags):
    lat = get_decimal_from_dms(geotags['GPSLatitude'], geotags['GPSLatitudeRef'])

    lon = get_decimal_from_dms(geotags['GPSLongitude'], geotags['GPSLongitudeRef'])

    return (lat,lon)



In [41]:
with wand.image.Image(filename='test.jpg') as img:
    img_resize = img.clone()
    print(img_resize.size)
    img_resize.resize(64,43)
    img_resize.format= 'jpeg'
    img_resize.save(filename='out.jpg')

(640, 428)


In [73]:
tmp1 = np.array(Image.open('test2.jpg'), dtype='float')
origin = np.array(Image.open('test.jpg'), dtype='float')
print(tmp1.shape)

(224, 224, 3)


In [58]:
np.mean(origin[:,:,0])

98.87767059948979

In [55]:
print(tmp1[:,:,0])

[[112. 112. 113. ...  70.  70.  72.]
 [112. 112. 113. ...  62.  64.  70.]
 [113. 113. 114. ...  57.  60.  68.]
 ...
 [ 77.  57.  62. ...  69.  53.  37.]
 [ 70.  53.  59. ...  62.  51.  45.]
 [ 59.  54.  51. ...  70.  55.  46.]]


In [66]:
os.path.join(os.getcwd(),'imgs_de')

'/Users/shuilingyu/Downloads/Granular/img_de'

In [72]:
os.listdir('imgs_de/corn')

['29028388068_12a831d91a_z.jpg',
 '45301165622_5be131c2d9_z.jpg',
 '43176046474_9d9ab8b3e8_z.jpg',
 '27937356207_b6674608bb_z.jpg',
 '43264680244_dd708bf3df_z.jpg',
 '28706682587_2379ac0c72_z.jpg',
 '.DS_Store',
 '42585324770_ce14332982_z.jpg',
 '32065557788_6b6caa3056_z.jpg',
 '30812628187_65a340080c_z.jpg',
 '41473183220_4d12155830_z.jpg',
 '44511484982_1636f6c307_z.jpg',
 '43099347421_dd5580ab1b_z.jpg',
 '42188038300_678c905eee_z.jpg',
 '45730733301_2a575cef88_z.jpg',
 '29638105108_bd4844c727_z.jpg',
 '31817412848_f9e2212208_z.jpg',
 '28828193857_3788ca1efd_z.jpg',
 '44737723882_57f7f514c4_z.jpg',
 '44967736222_c831fd055d_z.jpg',
 '30794952898_263583a4d0_z.jpg',
 '31584444338_4e66773cf8_z.jpg',
 '42823932164_5a8d6e87a7_z.jpg',
 '43309063240_51d00f37a9_z.jpg',
 '31504232518_72e9806148_z.jpg',
 '28957683777_796a5dbee8_z.jpg',
 '28731540748_754892aa85_z.jpg',
 '44850710041_591d956971_z.jpg',
 '41353303930_4894193542_z.jpg',
 '45407848642_42f5e43e15_z.jpg',
 '29708950837_305fea16c6_z.jp

In [59]:
exif = get_exif('test.jpg')
geotags = get_geotagging(exif)
print(get_coordinates(geotags))

ValueError: No EXIF metadata found

In [16]:
img.resize(64,27)

In [17]:
print(img.height, img.width)

27 64


In [10]:
type(img)

wand.image.Image